### ISSUE TITLE
NAPALM and Ansible 2.8 breaks on return_value import

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ansible#156]
```
The full traceback is:
Traceback (most recent call last):
  File "/Users/wmclendon/.ansible/tmp/ansible-tmp-1558468546.3411589-114490062578624/AnsiballZ_napalm_install_config.py", line 114, in <module>
    _ansiballz_main()
  File "/Users/wmclendon/.ansible/tmp/ansible-tmp-1558468546.3411589-114490062578624/AnsiballZ_napalm_install_config.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/wmclendon/.ansible/tmp/ansible-tmp-1558468546.3411589-114490062578624/AnsiballZ_napalm_install_config.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/var/folders/qd/41pypd4n2yd1rn9z6mh8bmbm0000gq/T/ansible_napalm_install_config_payload_I5zSNi/__main__.py", line 21, in <module>
ImportError: cannot import name return_values

fatal: [suw-mgmt-r03]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/Users/wmclendon/.ansible/tmp/ansible-tmp-1558468546.3411589-114490062578624/AnsiballZ_napalm_install_config.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/wmclendon/.ansible/tmp/ansible-tmp-1558468546.3411589-114490062578624/AnsiballZ_napalm_install_config.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/wmclendon/.ansible/tmp/ansible-tmp-1558468546.3411589-114490062578624/AnsiballZ_napalm_install_config.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/qd/41pypd4n2yd1rn9z6mh8bmbm0000gq/T/ansible_napalm_install_config_payload_I5zSNi/__main__.py\", line 21, in <module>\nImportError: cannot import name return_values\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by ktbyers** [comment]
Also need to update unit tests to test Ansible 2.8.

**Comment by ktbyers** [comment]
https://github.com/ansible/ansible/commit/aba4bed803fc783ea920798356eee196f7b56129#diff-90085fdcec6ed8b273ba885eaee60328

PR that broke this import

**Comment by ktbyers** [comment]
New method name looks like this

`_return_datastructure_name` (private now and not public)


Located here:

lib/ansible/module_utils/common/parameters.py

**Comment by TwoStroke42** [comment]
Hi ktbyers,

Did you have any workaround that you found for this? I'm pretty new to ansible and am hitting this error. Tried changing the import module to _return_datastructure_name but no success.

**Comment by ktbyers** [comment]
@TwoStroke42 Fix is here:

https://github.com/napalm-automation/napalm-ansible/pull/158

I also just merged that into the `develop` branch. I will probably do a new release shortly.
