### ISSUE TITLE
Trying to compare non-existend diff

### ISSUE THREAD

**Issue by t2d** [napalm-automation/napalm-ansible#6]
task:

```
- name: Push configuration with napalm
  napalm_install_config:
    hostname: "{{ inventory_hostname }}"
    dev_os: ios
    username: "{{ cisco_admins.0.username }}"
    password: "{{ cisco_admins.0.password }}"
    config_file: cisco-configs/{{ inventory_hostname }}/running-config
    commit_changes: False
    replace_config: False
    diff_file: cisco-config/{{ inventory_hostname }}/diff

```

ouput:

```
TASK: [cisco-ios | Push configuration with napalm] **************************** 
failed: [gw01ram1rls.ram1.rls.io] => {"failed": true, "parsed": false}
SSH connection established to gw01ram1rls.ram1.rls.io:22
Interactive SSH session established
+ service timestamps debug datetime msec
...
+ end
Traceback (most recent call last):
  File "/home/t/.ansible/tmp/ansible-tmp-1454334065.32-270842437256163/napalm_install_config", line 1792, in <module>
    main()
  File "/home/t/.ansible/tmp/ansible-tmp-1454334065.32-270842437256163/napalm_install_config", line 163, in main
    diff = device.compare_config().encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'


FATAL: all hosts have already failed -- aborting
```

**Comment by ktbyers** [comment]
@t2d What happens if you toggle: 

> replace_config: True

Obviously, only on a test/QA device. Note, this won't commit the change as commit_changes is still False.

Your above config isn't valid on Cisco IOS, you are doing a diff with a merge operation. Note, there still might be issues even after this change.

**Comment by t2d** [comment]
latest napalm(-ansible) gives me a new error:

```
failed: [host1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/t/.ansible/tmp/ansible-tmp-1456383584.32-109052819225727/napalm_install_config", line 1792, in <module>
    main()
  File "/home/t/.ansible/tmp/ansible-tmp-1456383584.32-109052819225727/napalm_install_config", line 170, in main
    save_to_file(diff, diff_file)
  File "/home/t/.ansible/tmp/ansible-tmp-1456383584.32-109052819225727/napalm_install_config", line 117, in save_to_file
    with open(filename, 'w') as f:
IOError: [Errno 2] No such file or directory: 'cisco-config/host1/diff'
```

@ktbyers `replace_config: True` results in the same error

**Comment by fooelisa** [comment]
This is ansible now trying to write the diff to a file into 'cisco-config/host1/diff' - does that dir exists from where you run ansible? You can adjust the dir with the diff_file parameter.

**Comment by t2d** [comment]
yes, the dir does exist. it is where I also read the config file from

```
- name: Push configuration with napalm
  napalm_install_config:
    hostname: "{{ inventory_hostname }}"
    dev_os: ios
    username: "{{ username }}"
    password: "{{ password }}"
    config_file: cisco-configs/{{ inventory_hostname }}/running-config
    commit_changes: False
    replace_config: False
    diff_file: cisco-config/{{ inventory_hostname }}/diff
```

**Comment by fooelisa** [comment]
note: "cisco-configs" vs. "cisco-config"

**Comment by t2d** [comment]
stupid me. works, thank you.
