### ISSUE TITLE
Fix napalm-ansible python3 compatibility

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm-ansible#88]
Add to unit tests.

This was testing Ansible 2.4.0 'devel' branch as of August29.

```
The full traceback is:
Traceback (most recent call last):
  File "/home/kbyers/VENV/ansible_test3/lib/python3.5/site-packages/ansible-2.4.0-py3.5.egg/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/home/kbyers/VENV/ansible_test3/lib/python3.5/site-packages/ansible-2.4.0-py3.5.egg/ansible/executor/task_executor.py", line 526, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/kbyers/VENV/ansible_test3/lib/python3.5/site-packages/ansible-2.4.0-py3.5.egg/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/home/kbyers/VENV/ansible_test3/lib/python3.5/site-packages/ansible-2.4.0-py3.5.egg/ansible/plugins/action/__init__.py", line 630, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/home/kbyers/VENV/ansible_test3/lib/python3.5/site-packages/ansible-2.4.0-py3.5.egg/ansible/plugins/action/__init__.py", line 165, in _configure_module
    environment=final_environment)
  File "/home/kbyers/VENV/ansible_test3/lib/python3.5/site-packages/ansible-2.4.0-py3.5.egg/ansible/executor/module_common.py", line 869, in modify_module
    environment=environment)
  File "/home/kbyers/VENV/ansible_test3/lib/python3.5/site-packages/ansible-2.4.0-py3.5.egg/ansible/executor/module_common.py", line 695, in _find_module_utils
    recursive_finder(module_name, b_module_data, py_module_names, py_module_cache, zf)
  File "/home/kbyers/VENV/ansible_test3/lib/python3.5/site-packages/ansible-2.4.0-py3.5.egg/ansible/executor/module_common.py", line 466, in recursive_finder
    tree = ast.parse(data)
  File "/usr/lib64/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 259
    except Exception, e:
```

**Comment by ktbyers** [comment]
Note, the above is an Ansible issue...try to get more clarity on Ansible + Python3 status.

**Comment by horseinthesky** [comment]
Was just reading your email about NAPALM in periodic mailings on Python and Network Automation course. 
I'm on Ansible 2.4.0 and Python3.5.2 on Ubuntu 16.04.03 and have similar issue. 
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ansible/executor/task_executor.py", line 125, in run
    res = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/ansible/executor/task_executor.py", line 528, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/action/normal.py", line 45, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars, wrap_async=wrap_async))
  File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/action/__init__.py", line 630, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/usr/local/lib/python3.5/dist-packages/ansible/plugins/action/__init__.py", line 165, in _configure_module
    environment=final_environment)
  File "/usr/local/lib/python3.5/dist-packages/ansible/executor/module_common.py", line 869, in modify_module
    environment=environment)
  File "/usr/local/lib/python3.5/dist-packages/ansible/executor/module_common.py", line 695, in _find_module_utils
    recursive_finder(module_name, b_module_data, py_module_names, py_module_cache, zf)
  File "/usr/local/lib/python3.5/dist-packages/ansible/executor/module_common.py", line 466, in recursive_finder
    tree = ast.parse(data)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 257
    except Exception, e:
                    ^
SyntaxError: invalid syntax

fatal: [10.10.30.1]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by ktbyers** [comment]
@horseinthesky Will fix...note, however, Ansible 2.4.0 doesn't support Python3.

**Comment by ktbyers** [comment]
The napalm-ansible specific PY3 bug that I am aware of are fixed here:

https://github.com/napalm-automation/napalm-ansible/pull/99
